on: [push]
jobs:
    foo:
        runs-on: ubuntu-latest
        steps:
            - name: "Hello world"
              run: echo "Hello World!"
    bar:
        runs-on: ubuntu-latest
        steps:
            - name: "Hello world22"
            - run: echo "hel"
